import { CheckCircle2, FileCog, Mic2, Play, RotateCcw } from "lucide-react";
import { useState } from "react";
import WorkflowUpload from "../components/WorkflowUpload";

type Area = "content" | "voice";
const areas = [{ id: "content" as const, title: "Content", subtitle: "APRM Content features file upload.", icon: FileCog }, { id: "voice" as const, title: "Voice", subtitle: "APRM Voice features file upload.", icon: Mic2 }];

export default function AprmRoute() {
  const [area, setArea] = useState<Area>("content"); const [processed, setProcessed] = useState<Record<Area, boolean>>({ content: false, voice: false });
  const selected = areas.find((item) => item.id === area)!; const Icon = selected.icon;
  return <div className="space-y-5"><section className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-black/[0.04]"><p className="text-[13px] font-medium text-[#007AFF]">APRM</p><h2 className="mt-1 text-[21px] font-bold tracking-tight text-[#1C1C1E]">APRM {selected.title}</h2><p className="mt-1 text-[13px] text-[#636366]">{selected.subtitle}</p><div className="mt-5 grid gap-2 sm:grid-cols-2">{areas.map((item) => { const AreaIcon = item.icon; const active = item.id === area; return <button key={item.id} onClick={() => setArea(item.id)} className={`focus-ring flex items-center gap-3 rounded-[12px] p-3 text-left transition ${active ? "bg-[#EAF2FF] ring-1 ring-[#007AFF]/20" : "bg-[#F2F2F7] hover:bg-[#E5E5EA]"}`}><span className={`grid h-10 w-10 place-items-center rounded-[10px] ${active ? "bg-[#007AFF] text-white" : "bg-white text-[#007AFF]"}`}><AreaIcon className="h-5 w-5" /></span><span><span className="block text-[14px] font-semibold text-[#1C1C1E]">APRM {item.title}</span><span className="mt-0.5 block text-[12px] text-[#636366]">{item.subtitle}</span></span></button>; })}</div></section><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><WorkflowUpload title={`APRM ${selected.title}`} description={selected.subtitle} acceptLabel="Supported source files" /><aside className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-black/[0.04]"><span className="grid h-10 w-10 place-items-center rounded-[10px] bg-[#EAF2FF] text-[#007AFF]"><Icon className="h-5 w-5" /></span><p className="mt-5 text-[13px] font-semibold text-[#1C1C1E]">APRM {selected.title}</p><p className="mt-1 text-[12px] leading-5 text-[#636366]">{selected.subtitle}</p><button onClick={() => setProcessed((current) => ({ ...current, [area]: true }))} className="focus-ring mt-5 inline-flex h-10 w-full items-center justify-center gap-2 rounded-[10px] bg-[#007AFF] text-[14px] font-semibold text-white hover:bg-[#006FE6]"><Play className="h-4 w-4" />Start processing</button>{processed[area] ? <div className="mt-4 flex items-center gap-2 rounded-[10px] bg-[#E9F9ED] px-3 py-2.5 text-[12px] font-medium text-[#248A3D]"><CheckCircle2 className="h-4 w-4" />Processing complete</div> : null}<button onClick={() => setProcessed((current) => ({ ...current, [area]: false }))} className="focus-ring mt-4 inline-flex items-center gap-2 text-[12px] font-medium text-[#636366] hover:text-[#007AFF]"><RotateCcw className="h-3.5 w-3.5" />Reset</button></aside></div></div>;
}
