import { ArrowRight, CheckCircle2, CloudUpload, FileWarning, Layers3, ShieldCheck, Sparkles, Zap } from "lucide-react";
import { Link } from "react-router-dom";
import { useUploadMode } from "../lib/uploadMode";

const workspaces = [
  { to: "/prepaid", title: "Prepaid Reclass", icon: Layers3, description: "Prepaid Reclass features file upload, import and manual data inputs.", detail: "2 files waiting", tone: "teal" },
  { to: "/memo", title: "MemoApp SST", icon: FileWarning, description: "Memo App Standard Source Templates features file upload and error or exception monitoring.", detail: "6 exceptions open", tone: "sky" },
  { to: "/aprm", title: "APRM", icon: Sparkles, description: "APRM features file upload.", detail: "Ready to process", tone: "violet" },
];

export default function DashboardRoute() {
  const { uploadMode } = useUploadMode();
  return <div className="space-y-16 pb-10 sm:space-y-20">
    <section className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-teal/18 via-sky-100 to-[#EDEAFF] px-6 py-10 sm:px-10 sm:py-14 lg:grid lg:min-h-[520px] lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:gap-10"><div className="absolute -left-24 -top-24 h-72 w-72 rounded-[4rem] bg-teal/20 blur-3xl" /><div className="absolute -bottom-24 -right-20 h-80 w-80 rounded-[5rem] bg-sky-400/20 blur-3xl" /><div className="relative"><span className="inline-flex items-center gap-2 rounded-full bg-white/75 px-3 py-1.5 text-[12px] font-semibold text-teal ring-1 ring-teal/15"><Sparkles className="h-3.5 w-3.5" />Data Transformation Plus</span><h1 className="font-heading mt-5 max-w-xl text-4xl font-extrabold leading-[1.08] tracking-tight text-slate-900 sm:text-5xl">DT<span className="text-teal">+</span></h1><p className="mt-5 max-w-xl text-[16px] leading-7 text-slate-600">Data Transformation Plus (DT+) streamlines your data management, offering a dynamic platform for enhancing your Extract, Transform, Load (ETL) processes. Simplify data uploads, monitor workflows, and execute tasks with ease, all through our intuitive interface. DT+ empowers users to actively correct and input data in real-time and generate insightful reports.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/prepaid" className="focus-ring inline-flex h-11 items-center gap-2 rounded-full bg-gradient-to-r from-teal to-sky-500 px-5 text-[14px] font-semibold text-white shadow-xl shadow-teal/20 transition hover:-translate-y-0.5">Learn more <ArrowRight className="h-4 w-4" /></Link><Link to="/memo" className="focus-ring inline-flex h-11 items-center rounded-full border border-slate-200 bg-white/80 px-5 text-[14px] font-semibold text-slate-700 transition hover:border-teal hover:text-teal">MemoApp SST</Link></div><div className="mt-7 flex items-center gap-2 text-[13px] text-slate-500"><ShieldCheck className="h-4 w-4 text-teal" />Private S3 storage and live transfer status</div></div>
      <div className="relative mt-10 lg:mt-0"><div className="mx-auto max-w-md rounded-[1.8rem] bg-white/90 p-5 shadow-2xl shadow-sky-700/10 ring-1 ring-white/80 backdrop-blur"><div className="flex items-center justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.08em] text-slate-400">Cycle snapshot</p><p className="font-heading mt-1 text-[20px] font-bold text-slate-900">Processing readiness</p></div><span className="grid h-10 w-10 place-items-center rounded-2xl bg-gradient-to-br from-teal/15 to-sky-100 text-teal"><CloudUpload className="h-5 w-5" /></span></div><div className="mt-5 grid grid-cols-3 gap-3"><div className="rounded-xl bg-gradient-to-br from-teal/10 to-teal/5 p-3"><p className="font-heading text-xl font-extrabold text-slate-900">3</p><p className="mt-1 text-[10px] font-medium text-slate-500">workspaces</p></div><div className="rounded-xl bg-sky-50 p-3"><p className="font-heading text-xl font-extrabold text-slate-900">2</p><p className="mt-1 text-[10px] font-medium text-slate-500">awaiting files</p></div><div className="rounded-xl bg-violet-50 p-3"><p className="font-heading text-xl font-extrabold text-slate-900">6</p><p className="mt-1 text-[10px] font-medium text-slate-500">exceptions</p></div></div><div className="mt-4 rounded-xl bg-slate-50 p-3.5"><div className="flex items-center justify-between text-[12px]"><span className="font-medium text-slate-600">Active transfer route</span><span className="rounded-full bg-white px-2.5 py-1 font-semibold text-teal shadow-sm">{uploadMode === "lambda" ? "Lambda upload" : "Direct S3"}</span></div></div><div className="mt-4 space-y-2.5">{["Prepaid source templates", "MemoApp SST template", "APRM Content and Voice"].map((item, index) => <div key={item} className="flex items-center gap-3 rounded-xl border border-slate-100 bg-white px-3 py-2.5"><span className={`grid h-7 w-7 place-items-center rounded-lg ${index === 1 ? "bg-amber-50 text-amber-500" : "bg-teal/10 text-teal"}`}><CheckCircle2 className="h-4 w-4" /></span><span className="flex-1 text-[12px] font-medium text-slate-600">{item}</span><span className="text-[11px] text-slate-400">{index === 1 ? "Review" : "Ready"}</span></div>)}</div></div></div></section>
    <section><div className="text-center"><p className="text-[12px] font-semibold uppercase tracking-[0.12em] text-teal">DT+ Modules</p><h2 className="font-heading mt-3 text-3xl font-extrabold tracking-tight text-slate-900">Prepaid Reclass, MemoApp SST, and APRM.</h2><p className="mx-auto mt-3 max-w-2xl text-[15px] leading-7 text-slate-500">Choose a module to upload files, review data, monitor exceptions, and run processing tasks.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{workspaces.map((workspace) => { const Icon = workspace.icon; const colors = workspace.tone === "teal" ? "from-teal/18 to-emerald-50 text-teal" : workspace.tone === "sky" ? "from-sky-100 to-indigo-50 text-sky-500" : "from-violet-100 to-fuchsia-50 text-violet-500"; return <Link key={workspace.to} to={workspace.to} className="group rounded-2xl bg-white p-6 shadow-lg shadow-slate-200/60 ring-1 ring-slate-100 transition hover:-translate-y-1 hover:shadow-xl"><span className={`grid h-11 w-11 place-items-center rounded-xl bg-gradient-to-br ${colors}`}><Icon className="h-5 w-5" /></span><h3 className="font-heading mt-6 text-[18px] font-bold text-slate-900">{workspace.title}</h3><p className="mt-2 min-h-12 text-[13px] leading-6 text-slate-500">{workspace.description}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><span className="text-[12px] font-medium text-slate-400">{workspace.detail}</span><span className="inline-flex items-center gap-1 text-[13px] font-semibold text-teal">Start processing <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></div></Link>; })}</div></section>
    <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl bg-gradient-to-br from-teal to-sky-500 p-7 text-white shadow-xl shadow-teal/20"><Zap className="h-5 w-5" /><h2 className="font-heading mt-8 text-2xl font-bold">Secure uploads, where you need them.</h2><p className="mt-3 max-w-md text-[14px] leading-6 text-white/85">Every workflow includes its own upload surface with progress, validation, retries, and private storage feedback.</p></div><div className="rounded-2xl border border-slate-100 bg-white p-7 shadow-lg shadow-slate-200/50"><p className="text-[12px] font-semibold uppercase tracking-[0.1em] text-teal">Current transfer</p><h2 className="font-heading mt-3 text-2xl font-bold text-slate-900">{uploadMode === "lambda" ? "Lambda upload is ready." : "Direct S3 is ready."}</h2><p className="mt-3 max-w-md text-[14px] leading-6 text-slate-500">Switch transfer methods at any time using the control in the header.</p></div></section>
  </div>;
}
