import { Download, FileWarning, MoreHorizontal } from "lucide-react";
import { useState } from "react";
import DemoTable from "../components/DemoTable";
import WorkflowUpload from "../components/WorkflowUpload";
import { memoErrors } from "../lib/demoData";

function exportErrors() { const content = ["Counter,Line item,Approval status,Reference,Vendor GL,Amount,Posting key,Header text,Exception", ...memoErrors.map((row) => row.join(","))].join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([content], { type: "text/csv" })); link.download = "memoapp-exceptions.csv"; link.click(); URL.revokeObjectURL(link.href); }

export default function MemoRoute() {
  const [tab, setTab] = useState<"upload" | "errors">("upload");
  return <div className="space-y-5"><section className="rounded-2xl bg-white px-5 py-5 shadow-sm ring-1 ring-black/[0.04]"><div className="flex items-start justify-between"><div><p className="text-[13px] font-medium text-[#007AFF]">MemoApp SST</p><h2 className="mt-1 text-[21px] font-bold tracking-tight text-[#1C1C1E]">{tab === "upload" ? "MemoApp Standard Source Template - File Upload." : "MemoApp Standard Source Template - Error Page."}</h2><p className="mt-1 text-[13px] text-[#636366]">{tab === "upload" ? "MemoApp Standard Source Templates features file upload and error or exception monitoring." : "Error or exception monitoring."}</p></div><button className="focus-ring grid h-9 w-9 place-items-center rounded-full text-[#8E8E93] hover:bg-[#F2F2F7]" aria-label="More MemoApp actions"><MoreHorizontal className="h-5 w-5" /></button></div><div className="mt-5 -mx-5 flex border-t border-[#E5E5EA] px-3 pt-2"><button onClick={() => setTab("upload")} className={`relative px-3 py-2.5 text-[13px] font-medium ${tab === "upload" ? "text-[#007AFF]" : "text-[#636366]"}`}>File Upload{tab === "upload" ? <span className="absolute inset-x-3 bottom-0 h-0.5 rounded-full bg-[#007AFF]" /> : null}</button><button onClick={() => setTab("errors")} className={`relative px-3 py-2.5 text-[13px] font-medium ${tab === "errors" ? "text-[#007AFF]" : "text-[#636366]"}`}>Error Page <span className="ml-1 rounded-full bg-[#FFF0F0] px-1.5 py-0.5 text-[10px] text-[#FF3B30]">{memoErrors.length}</span>{tab === "errors" ? <span className="absolute inset-x-3 bottom-0 h-0.5 rounded-full bg-[#007AFF]" /> : null}</button></div></section>
    {tab === "upload" ? <><WorkflowUpload title="MemoApp Standard Source Template - File Upload." description="Choose Files to upload a MemoApp Standard Source Template." acceptLabel="Accepted Format: MS Excel(xlsx)" multipleDirect={false} /><p className="text-[13px] text-[#636366]">Accepted Format: MS Excel(xlsx)</p></> : <><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2 text-[13px] text-[#636366]"><FileWarning className="h-4 w-4 text-[#FF9500]" />{memoErrors.length} records require review</div><button onClick={exportErrors} className="focus-ring inline-flex h-9 items-center gap-2 rounded-[10px] bg-[#007AFF] px-3 text-[13px] font-medium text-white hover:bg-[#006FE6]"><Download className="h-4 w-4" />Download Excel File</button></div><DemoTable ariaLabel="MemoApp errors" headers={["Action", "Counter", "Counter Line Item", "Approval Status", "Reference", "Vendor GL Act", "Amount In Doc Curr", "Posting Key", "Document Header Text", "Disabled Line Item"]} rows={memoErrors.map((row) => ["Open", ...row.slice(0, 8), "false"])} /></>}</div>;
}
