import { Check, Download, FileSpreadsheet, Lock, MoreHorizontal, Play, RefreshCcw, Snowflake, Unlock } from "lucide-react";
import { useMemo, useState } from "react";
import DemoTable from "../components/DemoTable";
import WorkflowUpload from "../components/WorkflowUpload";
import { allocationRows, layoutRows, prepaidSourceFiles } from "../lib/demoData";

type Tab = "files" | "eg" | "sg" | "allocation" | "jv" | "reports";
const tabs: Array<{ id: Tab; label: string }> = [{ id: "files", label: "File Upload" }, { id: "eg", label: "EG Layout" }, { id: "sg", label: "SG Layout" }, { id: "allocation", label: "Allocation" }, { id: "jv", label: "JV" }, { id: "reports", label: "Reports" }];

function downloadCsv() { const content = ["Revenue before reclass,Total gross,Total net", ...layoutRows.map((row) => [row[0], row[4], row[5]].join(","))].join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([content], { type: "text/csv" })); link.download = "prepaid-reclass-report.csv"; link.click(); URL.revokeObjectURL(link.href); }

export default function PrepaidRoute() {
  const [tab, setTab] = useState<Tab>("files"); const [frozen, setFrozen] = useState(false); const [validated, setValidated] = useState(false); const [notice, setNotice] = useState<string | null>(null);
  const title = useMemo(() => ({ files: "Prepaid Reclass - File Upload", eg: "Prepaid Systems 01 EG Layout", sg: "Prepaid Systems 51 SG Layout", allocation: "Prepaid Systems 02A EG MT Allocation", jv: "Prepaid Systems 03 EG JV", reports: "Prepaid Systems Report" })[tab], [tab]);
  const actionButton = "focus-ring inline-flex h-9 items-center gap-2 rounded-[10px] px-3 text-[13px] font-medium transition";
  return <div className="space-y-5"><section className="rounded-2xl bg-white px-5 py-5 shadow-sm ring-1 ring-black/[0.04]"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[13px] font-medium text-[#007AFF]">Prepaid Systems</p><h2 className="mt-1 text-[21px] font-bold tracking-tight text-[#1C1C1E]">{title}</h2><p className="mt-1 text-[13px] text-[#636366]">File upload, import and manual data inputs.</p></div><button className="focus-ring grid h-9 w-9 place-items-center rounded-full text-[#8E8E93] hover:bg-[#F2F2F7]" aria-label="More Prepaid Reclass actions"><MoreHorizontal className="h-5 w-5" /></button></div><div className="mt-5 -mx-5 overflow-x-auto border-t border-[#E5E5EA] px-3 pt-2" role="tablist">{tabs.map((item) => <button key={item.id} onClick={() => { setTab(item.id); setNotice(null); }} role="tab" aria-selected={tab === item.id} className={`relative whitespace-nowrap px-3 py-2.5 text-[13px] font-medium ${tab === item.id ? "text-[#007AFF]" : "text-[#636366] hover:text-[#1C1C1E]"}`}>{item.label}{tab === item.id ? <span className="absolute inset-x-3 bottom-0 h-0.5 rounded-full bg-[#007AFF]" /> : null}</button>)}</div></section>
    {notice ? <div className="flex items-center gap-2 rounded-[10px] bg-[#E9F9ED] px-3 py-2.5 text-[13px] text-[#248A3D]"><Check className="h-4 w-4" />{notice}</div> : null}
    {tab === "files" ? <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]"><WorkflowUpload title="Prepaid Reclass - File Upload" description="Select source files to upload for Prepaid Reclass processing." acceptLabel="Supported source files: PDF, Office documents, images, text, and ZIP" /><aside className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-black/[0.04]"><p className="text-[13px] font-semibold text-[#1C1C1E]">File Name</p><p className="mt-1 text-[12px] text-[#8E8E93]">Upload File</p><div className="mt-4 divide-y divide-[#E5E5EA]">{prepaidSourceFiles.map((file) => <div key={file} className="flex items-center gap-3 py-3"><span className="grid h-8 w-8 place-items-center rounded-[9px] bg-[#F2F2F7] text-[#007AFF]"><FileSpreadsheet className="h-4 w-4" /></span><span className="min-w-0 flex-1 truncate text-[12px] font-medium text-[#3A3A3C]">{file}</span><span className="text-[11px] text-[#8E8E93]">No file chosen</span></div>)}</div></aside></div> : null}
    {tab === "eg" || tab === "sg" ? <><div className="flex flex-wrap gap-2"><button onClick={() => setNotice("Layout restored to its last imported state.")} className={`${actionButton} bg-white text-[#3A3A3C] shadow-sm ring-1 ring-black/[0.04]`}><RefreshCcw className="h-4 w-4" />Reset</button><button onClick={() => setNotice("Demo import completed. Layout values are refreshed.")} className={`${actionButton} bg-[#007AFF] text-white hover:bg-[#006FE6]`}><Play className="h-4 w-4" />Import</button><button onClick={() => setFrozen((value) => !value)} className={`${actionButton} bg-[#1C1C1E] text-white hover:bg-black`}>{frozen ? <Unlock className="h-4 w-4" /> : <Snowflake className="h-4 w-4" />}{frozen ? "Un-Freeze" : "Freeze"}</button>{frozen ? <span className="inline-flex items-center gap-1 self-center text-[12px] font-medium text-[#636366]"><Lock className="h-3.5 w-3.5" />Layout locked</span> : null}</div><DemoTable ariaLabel="layout rows" headers={["REVENUES_BEFORE_RECLASS", "GP_EG_MT_Gross", "HY_EG_MT_Gross", "GP_EG_BB_Gross", "Total_Gross", "Total_Net", "Tier"]} rows={layoutRows} /></> : null}
    {tab === "allocation" ? <><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><button onClick={() => { setValidated(true); setNotice("Allocation validation completed with no blocking issues."); }} className={`${actionButton} bg-[#007AFF] text-white hover:bg-[#006FE6]`}><Check className="h-4 w-4" />Validate</button><select className="h-9 rounded-[10px] border-0 bg-white px-3 text-[13px] font-medium text-[#3A3A3C] shadow-sm ring-1 ring-black/[0.04]"><option>EG MT Allocation</option><option>EG BB Allocation</option><option>SG MT Allocation</option><option>SG BB Allocation</option></select></div>{validated ? <span className="rounded-full bg-[#E9F9ED] px-2.5 py-1 text-[12px] font-medium text-[#248A3D]">Validated</span> : null}</div><DemoTable ariaLabel="allocation rows" headers={["Period/year", "Cost element", "Revenue type", "Sub product group", "Unit", "Tax rate", "Average rate", "Amount", "Allocation %"]} rows={allocationRows} /></> : null}
    {tab === "jv" ? <DemoTable ariaLabel="journal voucher rows" headers={["Batch number", "Document date", "Posting date", "Doc type", "Company", "Currency", "Fiscal period", "Document number", "Text"]} rows={allocationRows.map((row, index) => [String(index + 1), "06/30/2026", "06/30/2026", "SA", "GLOB", "PHP", "06", "TOP-UP", row[3]])} /> : null}
    {tab === "reports" ? <section className="max-w-2xl rounded-2xl bg-white p-5 shadow-sm ring-1 ring-black/[0.04]"><p className="text-[13px] font-semibold text-[#1C1C1E]">Prepaid reclass report</p><p className="mt-1 text-[13px] text-[#636366]">Export the current demo layout values as a CSV file.</p><button onClick={downloadCsv} className="focus-ring mt-5 inline-flex h-10 items-center gap-2 rounded-[10px] bg-[#007AFF] px-4 text-[14px] font-semibold text-white hover:bg-[#006FE6]"><Download className="h-4 w-4" />Download report</button></section> : null}
  </div>;
}
