import { ArrowLeft, Download, FileWarning, LoaderCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import PageHeader from "../components/PageHeader";
import { fetchApiFile } from "../lib/apiClient";
import type { ProcessingPipelineStage } from "../lib/apiTypes";

const validStages = new Set<ProcessingPipelineStage>(["inbound", "outbound", "processed", "error"]);
export default function ProcessingPipelineFileViewRoute() { const [params] = useSearchParams(); const pipelineCode = params.get("pipelineCode") ?? ""; const stage = params.get("stage") ?? ""; const key = params.get("key") ?? ""; const [url, setUrl] = useState<string | null>(null); const [contentType, setContentType] = useState(""); const [error, setError] = useState<string | null>(null); useEffect(() => { if (!pipelineCode || !key || !validStages.has(stage as ProcessingPipelineStage)) { setError("This viewer link is incomplete or invalid."); return; } let objectUrl: string | null = null; void fetchApiFile(`/processing-pipelines/${encodeURIComponent(pipelineCode)}/files/content?${new URLSearchParams({ stage, key })}`).then((file) => { objectUrl = URL.createObjectURL(file.blob); setUrl(objectUrl); setContentType(file.contentType); }).catch((reason: Error) => setError(reason.message)); return () => { if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [key, pipelineCode, stage]); const filename = key.split("/").at(-1) ?? "Pipeline file"; const preview = contentType === "application/pdf" || contentType.startsWith("image/") || contentType.startsWith("text/"); return <div className="space-y-8 pb-4"><PageHeader eyebrow="Processing Pipelines" title={filename} description={`${pipelineCode} / ${stage}`}><Link to="/processing-pipelines" className="focus-ring inline-flex items-center gap-2 rounded-lg text-[13px] font-semibold text-teal"><ArrowLeft className="h-4 w-4" />Back to pipelines</Link></PageHeader><section className="portal-panel min-h-[420px] overflow-hidden p-5 sm:p-8">{error ? <p className="text-rose-700">{error}</p> : !url ? <p className="inline-flex items-center gap-2 text-sm text-slate-500"><LoaderCircle className="h-4 w-4 animate-spin" />Loading secure file</p> : preview ? <iframe title={filename} src={url} className="min-h-[70vh] w-full rounded-xl border border-slate-200" /> : <div className="text-center"><FileWarning className="mx-auto h-8 w-8 text-teal" /><p className="mt-4">Preview is not available for this file type.</p><a href={url} download={filename} className="focus-ring portal-button-primary mt-6"><Download className="h-4 w-4" />Download file</a></div>}</section></div>; }
